version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

  # we will use mongo as one of our sinks.
  # This configuration allows you to start mongo
  mongo:
    image: "mongo:4.2-bionic"
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: kafka-pool-messages
    volumes:
      - ./persistence/mongo/data/db:/data/db
      - ./persistence/mongo/data/backup:/data/backup
      - ./persistence/mongo/data/log/:/var/log/mongodb/
    ports:
      - "27017:27017"

  # we will use postgres as one of our sinks.
  # This configuration allows you to start postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: kafka-pool-entries  # define database
    ports:
      - 5432:5432                 # Postgres port
